# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant.configure("2") do |config|

  config.vm.box = "hashicorp/bionic64"

  # config.vm.synced_folder "../data", "/vagrant_data"

  # gitlabserver
  config.vm.define "gitlab" do |web|
    web.vm.provider "virtualbox" do |vb|
      vb.memory = 4092
      vb.cpus = 2
    end
    web.vm.network "private_network", ip: "192.168.33.10"
  end

  # gitlab runners
  config.vm.define "gitlabrunner1" do |runner|
    runner.vm.provider "virtualbox" do |vb|
      vb.memory = 2048
      vb.cpus = 2
    end
    
    runner.vm.hostname = "runner1"
    runner.vm.network "private_network", ip: "192.168.33.21"
  end

  # web dev env 
  config.vm.define "webdev" do |runner|
    runner.vm.provider "virtualbox" do |vb|
      vb.memory = 1024
      vb.cpus = 1
     end
     runner.vm.hostname = "webdev"
     runner.vm.network "private_network", ip: "192.168.33.31"
  end

end
