# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant.configure("2") do |config|

  config.vm.box = "hashicorp/bionic64"

  # config.vm.synced_folder "../data", "/vagrant_data"

  # Configure web server machine
  config.vm.define "gitlab" do |web|
    config.vm.provider "virtualbox" do |vb|
      vb.memory = 4096
      vb.cpus = 2
     end
    web.vm.network "private_network", ip: "192.168.33.10"
  end

end
