# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant.configure("2") do |config|

  config.vm.box = "hashicorp/bionic64"

  # config.vm.synced_folder "../data", "/vagrant_data"

  # Configure gitlabserver
  config.vm.define "gitlab" do |web|
    config.vm.provider "virtualbox" do |vb|
      vb.memory = 4096
      vb.cpus = 2
     end
    web.vm.network "private_network", ip: "192.168.33.10"
  end

  # Configure gitlab runners
  config.vm.define "gitlabrunner1" do |runner|
    config.vm.provider "virtualbox" do |vb|
      vb.memory = 1024
      vb.cpus = 1
     end
     runner.vm.hostname = "runner1"
     runner.vm.network "private_network", ip: "192.168.33.21"
  end

end
